name: API JAVALIN WORKFLOW
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'microsoft'
      -
        name: Build with Maven
        run: mvn --batch-mode --update-snapshots package
          -
          name: Login to Docker Hub
          uses: docker/login-action@v2 // This is a GitHub action that logs you into Dockerhub
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2 // This is a GitHub action that sets up Docker Buildx
            - name: Build and push
              uses: docker/build-push-action@v4 // This is a GitHub action that builds and pushes your Docker image
              with:
                context: .
                file: ./Dockerfile // This is the path to your Dockerfile
                push: true
                tags: ${{ secrets.DOCKERHUB_USERNAME }}/<NAME-OF-DOCKERHUB-REPOSITORY>:<DOCKER-TAG> // This is the name of your Dockerhub repository and the tag you want to give your image